export {
  defineConfig,
  definePlugin,
  defineBuildConfig,
  type Config,
  type LocalPluginsDefault,
  type ResolvedConfig,
  type Plugin,
  type PluginDependency,
  type ResolvedPlugin,
  type ResolvedPluginDependency,
  type BuildConfig,
  type ResolvedBuildConfig,
  type BundleConfig,
  type MirrorConfig,
  type BuildPlugin,
  type BuildContext,
  type EmitContext,
  type PackageManagerSpec,
} from "./cli/lib/build-config";

export {
  getConfig,
  subscribeConfig,
  getPlugins,
  getPlugin,
  getAppEntrypoint,
  getSplashPath,
  type ConfigSnapshot,
  type PluginRecord,
} from "./runtime";
