// Generated by: pnpm link:types
// DO NOT EDIT. Regenerated automatically (also wired into `prebuild`).

import type {
  BaseWindowService,
  DbService,
  HttpService,
  ReloaderService,
  RendererHostService,
  RpcService,
  ServerService,
  StateService,
  UpdaterService,
  ViewRegistryService,
  WindowService,
} from "@zenbujs/core/services"
import type { Events as Events_core } from "@zenbujs/core/events"
import type schema_core from "@zenbujs/core/schema"
import type { InferSchemaRoot } from "@zenbujs/core/db"

type ServiceBase =
  | "evaluate"
  | "shutdown"
  | "constructor"
  | "effect"
  | "__cleanupAllEffects"
  | "__effectCleanups"
  | "ctx"

type ExtractRpcMethods<T> = {
  [K in Exclude<keyof T, ServiceBase | `_${string}`> as T[K] extends (
    ...args: any[]
  ) => any
    ? K
    : never]: T[K]
}

import type { ServiceState } from "@zenbujs/core/runtime"

type ExtractStateFields<T> = {
  [K in Exclude<keyof T, ServiceBase | `_${string}`> as T[K] extends
    ServiceState<any>
    ? K
    : never]: T[K] extends ServiceState<infer V> ? V : never
}

export type CoreServiceRouter = {
  core: {
    "base-window": ExtractRpcMethods<BaseWindowService>;
    db: ExtractRpcMethods<DbService>;
    http: ExtractRpcMethods<HttpService>;
    reloader: ExtractRpcMethods<ReloaderService>;
    "renderer-host": ExtractRpcMethods<RendererHostService>;
    rpc: ExtractRpcMethods<RpcService>;
    server: ExtractRpcMethods<ServerService>;
    state: ExtractRpcMethods<StateService>;
    updater: ExtractRpcMethods<UpdaterService>;
    "view-registry": ExtractRpcMethods<ViewRegistryService>;
    window: ExtractRpcMethods<WindowService>;
  };
}

export type CoreServiceStates = {
  core: {
    "base-window": ExtractStateFields<BaseWindowService>;
    db: ExtractStateFields<DbService>;
    http: ExtractStateFields<HttpService>;
    reloader: ExtractStateFields<ReloaderService>;
    "renderer-host": ExtractStateFields<RendererHostService>;
    rpc: ExtractStateFields<RpcService>;
    server: ExtractStateFields<ServerService>;
    state: ExtractStateFields<StateService>;
    updater: ExtractStateFields<UpdaterService>;
    "view-registry": ExtractStateFields<ViewRegistryService>;
    window: ExtractStateFields<WindowService>;
  };
}

export type CoreEvents = { core: Events_core }

export type CoreDbSections = {
  core: InferSchemaRoot<typeof schema_core>;
}

export type CorePreloads = {}
