// Generated by: pnpm link:types
// DO NOT EDIT. Regenerated automatically (also wired into `prebuild`).

import type {
  BaseWindowService,
  BootTraceService,
  DbService,
  FunctionRegistryService,
  HttpService,
  PluginUpdaterService,
  ReloaderService,
  RendererHostService,
  RpcService,
  ServerService,
  ShortcutsService,
  UpdaterService,
  ViewRegistryService,
  WindowService,
} from "@zenbujs/core/services"
import type { Events as Events_core } from "@zenbujs/core/events"
import type schema_core from "@zenbujs/core/schema"
import type { InferSchemaRoot } from "@zenbujs/core/db"

type ServiceBase =
  | "evaluate"
  | "shutdown"
  | "constructor"
  | "effect"
  | "__cleanupAllEffects"
  | "__effectCleanups"
  | "ctx"

type ExtractRpcMethods<T> = {
  [K in Exclude<keyof T, ServiceBase | `_${string}`> as T[K] extends (
    ...args: any[]
  ) => any
    ? K
    : never]: T[K]
}

export type CoreServiceRouter = {
  core: {
    baseWindow: ExtractRpcMethods<BaseWindowService>;
    bootTrace: ExtractRpcMethods<BootTraceService>;
    db: ExtractRpcMethods<DbService>;
    functionRegistry: ExtractRpcMethods<FunctionRegistryService>;
    http: ExtractRpcMethods<HttpService>;
    pluginUpdater: ExtractRpcMethods<PluginUpdaterService>;
    reloader: ExtractRpcMethods<ReloaderService>;
    rendererHost: ExtractRpcMethods<RendererHostService>;
    rpc: ExtractRpcMethods<RpcService>;
    server: ExtractRpcMethods<ServerService>;
    shortcuts: ExtractRpcMethods<ShortcutsService>;
    updater: ExtractRpcMethods<UpdaterService>;
    viewRegistry: ExtractRpcMethods<ViewRegistryService>;
    window: ExtractRpcMethods<WindowService>;
  };
}

export type CoreEvents = { core: Events_core }

export type CoreDbSections = {
  core: InferSchemaRoot<typeof schema_core>;
}

export type CorePreloads = {}
