// Generated by: pnpm link:types
// DO NOT EDIT. Local-only augmentation (NOT shipped via package.json#files).
// Drives core's own typecheck so useRpc()/useEvents()/useDb()/useServiceState()
// resolve to the registered surface inside packages/core/src/.

import type {} from "@zenbujs/core/registry"
import type {
  CoreServiceRouter,
  CoreServiceStates,
  CoreEvents,
  CoreDbSections,
} from "../src/registry-generated"

declare module "@zenbujs/core/registry" {
  interface ZenbuRegister {
    rpc: CoreServiceRouter
    state: CoreServiceStates
    events: CoreEvents
    db: CoreDbSections
  }
}

export {}
